version: '3'

services:
  api-solid-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    enviroments:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=root
      - POSTGRESQL_DATABASE=apisolid