name: Run Unit Tests

on: [push]

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - run: rm -rf node_modules # remove node_modules antes da instalação
      - run: npm ci # instala dependencias

      - run: npm run test # executa os testes
